# Generated by Django 4.2.1 on 2023-07-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodcut',
            name='sale_price',
        ),
    ]
