# Generated by Django 2.2.4 on 2023-07-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0002_orders_prodcuts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Prodcuts',
            new_name='Prodcut',
        ),
    ]
